package require Tk
package require Ttk
wm title . "deez nuts"
label .x_cursor -text X_cursor -cursor X_cursor
grid .x_cursor -row 0 -column 1
label .arrow -text arrow -cursor arrow
grid .arrow -row 1 -column 1
label .based_arrow_down -text based_arrow_down -cursor based_arrow_down
grid .based_arrow_down -row 2 -column 1
label .based_arrow_up -text based_arrow_up -cursor based_arrow_up
grid .based_arrow_up -row 3 -column 1
label .boat -text boat -cursor boat
grid .boat -row 4 -column 1
label .bogosity -text bogosity -cursor bogosity
grid .bogosity -row 5 -column 1
label .bottom_left_corner -text bottom_left_corner -cursor bottom_left_corner
grid .bottom_left_corner -row 6 -column 1
label .bottom_right_corner -text bottom_right_corner -cursor bottom_right_corner
grid .bottom_right_corner -row 7 -column 1
label .bottom_side -text bottom_side -cursor bottom_side
grid .bottom_side -row 8 -column 1
label .bottom_tee -text bottom_tee -cursor bottom_tee
grid .bottom_tee -row 9 -column 1
label .box_spiral -text box_spiral -cursor box_spiral
grid .box_spiral -row 10 -column 1
label .center_ptr -text center_ptr -cursor center_ptr
grid .center_ptr -row 11 -column 1
label .circle -text circle -cursor circle
grid .circle -row 12 -column 1
label .clock -text clock -cursor clock
grid .clock -row 13 -column 1
label .coffee_mug -text coffee_mug -cursor coffee_mug
grid .coffee_mug -row 14 -column 1
label .cross -text cross -cursor cross
grid .cross -row 15 -column 1
label .cross_reverse -text cross_reverse -cursor cross_reverse
grid .cross_reverse -row 16 -column 1
label .crosshair -text crosshair -cursor crosshair
grid .crosshair -row 17 -column 1
label .diamond_cross -text diamond_cross -cursor diamond_cross
grid .diamond_cross -row 18 -column 1
label .dot -text dot -cursor dot
grid .dot -row 19 -column 1
label .dotbox -text dotbox -cursor dotbox
grid .dotbox -row 20 -column 1
label .double_arrow -text double_arrow -cursor double_arrow
grid .double_arrow -row 21 -column 1
label .draft_large -text draft_large -cursor draft_large
grid .draft_large -row 22 -column 1
label .draft_small -text draft_small -cursor draft_small
grid .draft_small -row 23 -column 1
label .draped_box -text draped_box -cursor draped_box
grid .draped_box -row 24 -column 1
label .exchange -text exchange -cursor exchange
grid .exchange -row 25 -column 1
label .fleur -text fleur -cursor fleur
grid .fleur -row 26 -column 1
label .gobbler -text gobbler -cursor gobbler
grid .gobbler -row 27 -column 1
label .gumby -text gumby -cursor gumby
grid .gumby -row 28 -column 1
label .hand1 -text hand1 -cursor hand1
grid .hand1 -row 29 -column 1
label .hand2 -text hand2 -cursor hand2
grid .hand2 -row 0 -column 2
label .heart -text heart -cursor heart
grid .heart -row 1 -column 2
label .icon -text icon -cursor icon
grid .icon -row 2 -column 2
label .iron_cross -text iron_cross -cursor iron_cross
grid .iron_cross -row 3 -column 2
label .left_ptr -text left_ptr -cursor left_ptr
grid .left_ptr -row 4 -column 2
label .left_side -text left_side -cursor left_side
grid .left_side -row 5 -column 2
label .left_tee -text left_tee -cursor left_tee
grid .left_tee -row 6 -column 2
label .leftbutton -text leftbutton -cursor leftbutton
grid .leftbutton -row 7 -column 2
label .ll_angle -text ll_angle -cursor ll_angle
grid .ll_angle -row 8 -column 2
label .lr_angle -text lr_angle -cursor lr_angle
grid .lr_angle -row 9 -column 2
label .man -text man -cursor man
grid .man -row 10 -column 2
label .middlebutton -text middlebutton -cursor middlebutton
grid .middlebutton -row 11 -column 2
label .mouse -text mouse -cursor mouse
grid .mouse -row 12 -column 2
label .none -text none -cursor none
grid .none -row 13 -column 2
label .pencil -text pencil -cursor pencil
grid .pencil -row 14 -column 2
label .pirate -text pirate -cursor pirate
grid .pirate -row 15 -column 2
label .plus -text plus -cursor plus
grid .plus -row 16 -column 2
label .question_arrow -text question_arrow -cursor question_arrow
grid .question_arrow -row 17 -column 2
label .right_ptr -text right_ptr -cursor right_ptr
grid .right_ptr -row 18 -column 2
label .right_side -text right_side -cursor right_side
grid .right_side -row 19 -column 2
label .right_tee -text right_tee -cursor right_tee
grid .right_tee -row 20 -column 2
label .rightbutton -text rightbutton -cursor rightbutton
grid .rightbutton -row 21 -column 2
label .rtl_logo -text rtl_logo -cursor rtl_logo
grid .rtl_logo -row 22 -column 2
label .sailboat -text sailboat -cursor sailboat
grid .sailboat -row 23 -column 2
label .sb_down_arrow -text sb_down_arrow -cursor sb_down_arrow
grid .sb_down_arrow -row 24 -column 2
label .sb_h_double_arrow -text sb_h_double_arrow -cursor sb_h_double_arrow
grid .sb_h_double_arrow -row 25 -column 2
label .sb_left_arrow -text sb_left_arrow -cursor sb_left_arrow
grid .sb_left_arrow -row 26 -column 2
label .sb_right_arrow -text sb_right_arrow -cursor sb_right_arrow
grid .sb_right_arrow -row 27 -column 2
label .sb_up_arrow -text sb_up_arrow -cursor sb_up_arrow
grid .sb_up_arrow -row 28 -column 2
label .sb_v_double_arrow -text sb_v_double_arrow -cursor sb_v_double_arrow
grid .sb_v_double_arrow -row 29 -column 2
label .shuttle -text shuttle -cursor shuttle
grid .shuttle -row 0 -column 3
label .sizing -text sizing -cursor sizing
grid .sizing -row 1 -column 3
label .spider -text spider -cursor spider
grid .spider -row 2 -column 3
label .spraycan -text spraycan -cursor spraycan
grid .spraycan -row 3 -column 3
label .star -text star -cursor star
grid .star -row 4 -column 3
label .target -text target -cursor target
grid .target -row 5 -column 3
label .tcross -text tcross -cursor tcross
grid .tcross -row 6 -column 3
label .top_left_arrow -text top_left_arrow -cursor top_left_arrow
grid .top_left_arrow -row 7 -column 3
label .top_left_corner -text top_left_corner -cursor top_left_corner
grid .top_left_corner -row 8 -column 3
label .top_right_corner -text top_right_corner -cursor top_right_corner
grid .top_right_corner -row 9 -column 3
label .top_side -text top_side -cursor top_side
grid .top_side -row 10 -column 3
label .top_tee -text top_tee -cursor top_tee
grid .top_tee -row 11 -column 3
label .trek -text trek -cursor trek
grid .trek -row 12 -column 3
label .ul_angle -text ul_angle -cursor ul_angle
grid .ul_angle -row 13 -column 3
label .umbrella -text umbrella -cursor umbrella
grid .umbrella -row 14 -column 3
label .ur_angle -text ur_angle -cursor ur_angle
grid .ur_angle -row 15 -column 3
label .watch -text watch -cursor watch
grid .watch -row 16 -column 3
label .xterm -text xterm -cursor xterm
grid .xterm -row 17 -column 3
label .no -text no -cursor no
grid .no -row 18 -column 3
label .starting -text starting -cursor starting
grid .starting -row 19 -column 3
label .size -text size -cursor size
grid .size -row 20 -column 3
label .size_ne_sw -text size_ne_sw -cursor size_ne_sw
grid .size_ne_sw -row 21 -column 3
label .size_ns -text size_ns -cursor size_ns
grid .size_ns -row 22 -column 3
label .size_nw_se -text size_nw_se -cursor size_nw_se
grid .size_nw_se -row 23 -column 3
label .size_we -text size_we -cursor size_we
grid .size_we -row 24 -column 3
label .uparrow -text uparrow -cursor uparrow
grid .uparrow -row 25 -column 3
label .wait -text wait -cursor wait
grid .wait -row 26 -column 3